#!/bin/sh
COMPILE_FLAGS="-march=native -std=c++11 -D_DEBUG -O0 -g"
g++ $COMPILE_FLAGS -o main.g++.o -c main.cpp
g++ $COMPILE_FLAGS -o SpookyHash/SpookyV2.g++.o -c SpookyHash/SpookyV2.cpp
g++ -g -o hash-table-tests.g++ main.g++.o SpookyHash/SpookyV2.g++.o
